Use different Bugzilla comment when translation is missing
mozfr/transvision pull request #1033
Opened 2023-04-07 21:00 UTC by enderandpeter

#827 

# The Problem

After clicking the "report a bug" link for a missing target translation, the Bugzilla comment contains the **@@missing@@** tag used internally by this application.

# The Solution

When the Bugzilla comment is created for the "report a bug" link, and the target translation is missing, use a default comment that pertains to this situation, for example:

```
Source string:
Content crashed

This string has not been translated yet. Proposed translation:
```

# Notes

I have a simple solution in place that will use the above template if the `$target_string` in `Bugzilla::reportErrorLink` is `@@missing@@`. `tests/units/Transvision/Bugzilla.php` has been updated to test for this case. See if you can think of other cases we may want to test.

This is my first contribution to this project, so I apologize if I missed something. I did run `php-cs-fixer` on the changes files. I hope the other tests still pass, but I will do what is necessary to fix any problems. Let me know what you think. Thank you!

2023-04-08 05:52 UTC, flodolo requested changes
This looks great and works, but it also made me realize there is more space for improvement. In the almost 10 years since this code was originally written, Bugzilla has introduced support for Markdown, which can help us a lot here.

We can use code blocks for source/translation, and an actual link instead of the huge Transvision URL. Also, to simplify code a bit, we can use the same preamble (`Source string:`) for both scenarios.

Example:

```php
$message = "Source string:\n\n```\n{$source_string}\n```\n\n";
if($target_string !== '@@missing@@') {
    $message .= "Is translated as:\n\n```\n{$target_string}\n```\n\n"
        . "And should be:\n\n```\n(add your translation here)\n```\n\n";
} else {
    // If the target string has the @@missing@@ tag, use an alternative comment
    $message .= "This string has not been translated yet. Proposed translation:\n\n"
        . "```\n(add your translation here)\n```\n\n";
}
// Add link to the string in Transvision
$message .= "Feedback via [Transvision]({$transvision_url}).";
$bug_message = rawurlencode(
    html_entity_decode($message)
);
```

Feel free to change/improve it, but that should be the general idea (only tested with a couple of strings).

2023-04-08 05:52 UTC, flodolo commented on app/classes/Transvision/Bugzilla.php
> +        // If the target string has the @@missing@@ tag, use an alternate comment
```suggestion
        // If the target string has the @@missing@@ tag, use an alternative comment
```

2023-04-09 23:34 UTC, enderandpeter commented
I was able to incorporate the changes you suggested. Things appear to be working as expected. Here are some previews of the Bugzilla comment:

## New comment, string missing

![New Bugzilla Comment_String Missing](https://user-images.githubusercontent.com/4011193/230801501-06e3ac5d-3138-401b-a061-b67c1e438ec3.png)

## String Not Missing

![New Bugzilla Comment_String Not Missing](https://user-images.githubusercontent.com/4011193/230801524-1dfc764f-53e0-4294-ab9b-02c38b23dabd.png)

## Complex String Missing

![New Bugzilla Comment_Complex String Missing](https://user-images.githubusercontent.com/4011193/230801536-9ff97f7f-e1aa-4cae-a20d-f8536aa9f022.png)

## Complex String Not Missing

![New Bugzilla Comment_Complex String Not Missing](https://user-images.githubusercontent.com/4011193/230801547-7904c9c1-5b87-4350-81b9-a648f0e1d442.png)

I'm wondering if the newlines insides the preformatted blocks should be removed? It appears they are creating several spaces instead of an actual newline.

2023-04-10 05:35 UTC, flodolo commented
> Actually, I do see the newlines now. I think the indentation threw me off. Not sure where that is from.

Not sure if [this](https://transvision.flod.org/?sourcelocale=en-US&locale=af&repo=all_projects&search_type=entities&recherche=android_l10n/mozilla-mobile/android-components/components/browser/errorpages/src/main/res/values/strings.xml:mozac_browser_errorpages_safe_browsing_malware_uri_message&entire_string=entire_string) is the string in your second example, but there are spaces in the source

```
    <string name="mozac_browser_errorpages_safe_browsing_malware_uri_message"><![CDATA[
      <p>The site at %1$s has been reported as an attack site and has been blocked based on your security preferences.</p>
    ]]></string>
```

If you inspect the results table, and set `white-space: pre`, you'll see them.

![Screenshot 2023-04-10 alle 07 35 14](https://user-images.githubusercontent.com/3644868/230833421-cf0e3b86-b955-42c2-8609-4fecf3df5ea6.png)

2023-04-10 05:38 UTC, flodolo approved these changes
Congrats for your first contribution.

This will be available in a few minutes in my own server (running beta), and deployed in production in the coming days (hopefully we can figure out the issue with All Projects and deploy both).

2023-04-10 05:39 UTC, merged

2023-04-10 16:19 UTC, enderandpeter commented
Heck yeah. Thank you so much!